In [ ]:
import sys
# Check Python version
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
  print("Hello, World!")
  print(f"Python version: {sys.version}")
else:
  print("Please use Python 3.6 or higher.")

Hello, World!
Python version: 3.11.11 (main, Dec  4 2024, 08:55:07) [GCC 11.4.0]


In [ ]:
# Mutable Data Type Example (List)
my_list = [1, 2, 3]
print("Original List:", my_list)
my_list.append(4)
print("Modified List:", my_list)
my_tuple = (1, 2, 3)
print("Original Tuple:", my_tuple)

Original List: [1, 2, 3]
Modified List: [1, 2, 3, 4]
Original Tuple: (1, 2, 3)


In [ ]:
age = 23 #int
pi = 3.14 #float
temperature = -5.5 #float
print("data type of variable age = ", type(age))
print("data type of variable pi = ", type(pi))
print("data type of variable temperature = ", type(temperature))

data type of variable age =  <class 'int'>
data type of variable pi =  <class 'float'>
data type of variable temperature =  <class 'float'>


In [ ]:
name = "Alice"
greeting = 'Hello'
address = "123 Main St"
print("data type of the variable name = ",type(name))
print("data type of the variable greeting = ",type(greeting))
print("data type of the variable address = ",type(address))
# slice only one element
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])
# slice a range of elements
print("The second letter to the fourth of the name is:", name[1:4])
print("The first two letters of the name are:", name[:2])
print("Substring starting from the third letter is:", name[2:])

data type of the variable name =  <class 'str'>
data type of the variable greeting =  <class 'str'>
data type of the variable address =  <class 'str'>
The first letter of the name is: A
The last letter of the name is: e
The second letter to the fourth of the name is: lic
The first two letters of the name are: Al
Substring starting from the third letter is: ice


In [ ]:
list1 = [1, 2, 3, 4]
mixed_list = [12, "Hello", True]
# List is mutable
mixed_list[0] = False
mixed_list

[False, 'Hello', True]

In [ ]:
colors = ('red', 'green', 'yellow', 'blue')
print("First element:", colors[0])
print("Last two elements:", colors[2:])
print("Middle two elements:", colors[1:3])

First element: red
Last two elements: ('yellow', 'blue')
Middle two elements: ('green', 'yellow')


In [ ]:
person = {'name':'John','age':30,'city':'Pittsburgh'}
print(f"Hello my name is {person['name']}. I am {person['age']} years old and I live at {person['city']}.")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))

Hello my name is John. I am 30 years old and I live at Pittsburgh.
All keys: ['name', 'age', 'city']
All values: ['John', 30, 'Pittsburgh']


In [ ]:
unique_numbers = {1,2,3,3,3,3,4,5}
print(unique_numbers)

{1, 2, 3, 4, 5}


In [ ]:
is_student = True
has_license = False
print("data type of the variable is_student = ",type(is_student))
print("data type of the variable has_license = ",type(has_license))

data type of the variable is_student =  <class 'bool'>
data type of the variable has_license =  <class 'bool'>


## To-do task

4.1 Exercise on function:

# Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.

• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [ ]:
def Length(unit,value):
  if unit=="m":
    return value * 3.28084
  elif unit=="ft":
    return value * 0.3048
  else:
    raise ValueError("Invalid unit. Use 'm' or 'ft'.")

def Weight(unit,value):
  if unit=="kg":
    return value * 2.20462
  elif unit=="lbs":
    return value * 0.453592
  else:
    raise ValueError("Invalid unit. Use 'kg' or 'lbs'.")

def Volume(unit,value):
  if unit=="L":
    return value * 0.26417
  elif unit=="gal":
    return value * 3.78541
  else:
    raise ValueError("Invalid unit. Use 'L' or 'gal'.")


def main():
  print("Choose a type of conversion: \n 1.Length(m<->ft) \n 2.Weight(kg<->lbs) \n 3.Volume(L<->gal)")
  try:
    choice = int(input("Enter your choice(1-3): "));
    if choice==1:
      unit= input("Enter unit (m/ft): ").lower()
      value= float(input("Enter value: "))
      result= Length(unit,value)
      converted_unit="ft" if unit =="m" else "m"
    elif choice==2:
      unit= input("Enter unit (kg/lbs): ").lower()
      value= float(input("Enter value: "))
      result= Weight(unit,value)
      converted_unit="lbs" if unit =="kg" else "kg"
    elif choice==3:
      unit= input("Enter unit (L/gal): ").lower()
      value= float(input("Enter value: "))
      result= Volume(unit,value)
      converted_unit="gal" if unit =="L" else "L"
    else:
      print("Invalid choice")
      return

    print(f"Converted Value: {result:.2f} {converted_unit}")
  except ValueError:
    print("Invalid input. Please enter a valid number.")
  except Exception as e:
    print(f"An error occurred: {e}")

if __name__=="__main__":
  main()

Choose a type of conversion: 
 1.Length(m<->ft) 
 2.Weight(kg<->lbs) 
 3.Volume(L<->gal)
Enter your choice(1-3): 2
Enter unit (kg/lbs): kg
Enter value: 30
Converted Value: 66.14 lbs


# Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

• Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def calculate_sum(numbers):
    print(f"Calculating sum for: {numbers}")
    return sum(numbers)

def calculate_average(numbers):
    print(f"Calculating average for: {numbers}")
    return sum(numbers) / len(numbers) if numbers else 0

def find_maximum(numbers):
    print(f"Finding maximum for: {numbers}")
    return max(numbers)

def find_minimum(numbers):
    print(f"Finding minimum for: {numbers}")
    return min(numbers)


def main():
    print("Choose an operation: \n1.Sum \n2.Average \n3.Maximum \n4.Minimum")
    try:
        choice = int(input("Enter your choice(1-4): "))
        if choice not in [1, 2, 3, 4]:
            print("Invalid choice. Number should be between 1 and 4.")
            return

        numbers = input("Enter a list of numbers (separated by spaces): ").split()
        if not numbers:  # Handle case where input is empty
            print("Invalid input. Please enter a non-empty list of numbers.")
            return

        numbers = [float(num) for num in numbers]

        if choice == 1:
            result = calculate_sum(numbers)
            print(f"Sum: {result}")
        elif choice == 2:
            result = calculate_average(numbers)
            print(f"Average: {result}")
        elif choice == 3:
            result = find_maximum(numbers)
            print(f"Maximum: {result}")
        elif choice == 4:
            result = find_minimum(numbers)
            print(f"Minimum: {result}")

    except ValueError:
        print("Invalid input. Please enter numeric values only.")
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    main()


Choose an operation: 
1.Sum 
2.Average 
3.Maximum 
4.Minimum
Enter your choice(1-4): 3
Enter a list of numbers (separated by spaces): 2 3
Finding maximum for: [2.0, 3.0]
Maximum: 3.0


## 4.2 Exercise on List Manipulation:

1. Extract Every Other Element:

Write a Python function that extracts every other element from a list, starting from the first element.

In [ ]:
def extract_every_other(lst):
  return lst[::2]

print(extract_every_other([1,2,3,4,5,6]))

[1, 3, 5]


2. Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

In [ ]:
def get_sublist(lst, start, end):
  return lst[start:end+1]

print(get_sublist([1,2,3,4,5,6],2,4))

[3, 4, 5]


3. Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.

In [ ]:
def reverse_list(lst):
  return lst[::-1];

print(reverse_list([1,2,3,4,5]))

[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

In [ ]:
def remove_first_last(lst):
  return lst[1:-1]

print(remove_first_last([1,2,3,4,5]))

[2, 3, 4]


5. Get the First n Elements:

Write a Python function that extracts the first n elements from a list.

In [ ]:
def get_first_n(lst,n):
  return lst[0:n]

print(get_first_n([1,2,3,4,5],3))

[1, 2, 3]


6. Extract Elements from the End:

Write a Python function that extracts the last n elements of a list using slicing.

In [ ]:
def get_last_n(lst,n):
  return lst[-n:]

print(get_last_n([1,2,3,4,5],3))

[3, 4, 5]


7. Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

In [ ]:
def reverse_skip(lst):
  return lst[-2::-2]

print(reverse_skip([1,2,3,4,5,6]))

[5, 3, 1]


# Exercise on Nested List:

1. Flatten a Nested List:

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

In [ ]:
def flatten(lst):
  flat_list=[]
  for sublist in lst:
    flat_list.extend(sublist)
  return flat_list

print(flatten([[1,2],[3,4],[5]]))

[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:

Write a Python function that extracts a specific element from a nested list given its indices.

In [ ]:
def access_nested_element(lst, indices):
  return lst[indices[0]][indices[1]]

print(access_nested_element([[1,2,3],[4,5,6],[7,8,9]],[1,2]))

6


3. Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [ ]:
def sum_nested(lst):
    total = 0

    for element in lst:
        if isinstance(element, list):
            total += sum_nested(element)
        else:
            total += element
    return total
print(sum_nested([[1, 2], [3, [4, 5]], 6]))

21


4. Remove Specific Element from a Nested List:

Write a Python function that removes all occurrences of a specific element from a nested list.

In [ ]:
def remove_element(lst, elem):
  result=[]

  for item in lst:
    if isinstance(item, list):
      filtered_sublist= remove_element(item, elem)
      if filtered_sublist:
        result.append(filtered_sublist)
    elif item != elem:
      result.append(item)
  return result

print(remove_element([[1,2],[3,2],[4,5]],2))

[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:

Write a Python function that finds the maximum element in a nested list (regardless of depth).


In [ ]:
def find_max_in_nested_list(nested_list):
    max_value = float('-inf')

    for element in nested_list:
        if isinstance(element, list):
            max_value = max(max_value, find_max_in_nested_list(element))
        else:
            max_value = max(max_value, element)

    return max_value

nested_list = [1, [4, 6, [8, 3]], [10, [15, 2], 7], 5]
print("Maximum element:", find_max_in_nested_list(nested_list))


Maximum element: 15


6. Count Occurrences of an Element in a Nested List:

Write a Python function that counts how many times a specific element appears in a nested list.

In [ ]:
def count_occurrences(nested_list, target):
    count = 0

    for element in nested_list:
        if isinstance(element, list):
            count += count_occurrences(element, target)
        elif element == target:
            count += 1

    return count

nested_list = [1, [2, 3, [4, 2, 2]], [5, [2, 6], 2], 2]
target_element = 2
print(f"Occurrences of {target_element}:", count_occurrences(nested_list, target_element))


Occurrences of 2: 6


7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [3]:
def flatten_list(nested_list):
    flat_list = []

    for element in nested_list:
        if isinstance(element, list):
            flat_list.extend(flatten_list(element))
        else:
            flat_list.append(element)

    return flat_list

nested_list = [1, [2, [3, 4], 5], [[6, 7], 8], 9]
print("Flattened List:", flatten_list(nested_list))


Flattened List: [1, 2, 3, 4, 5, 6, 7, 8, 9]


8. Nested List Average:

Write a Python function that calculates the average of all elements in a nested list.

In [4]:
def calculate_average(nested_list):
    total_sum = 0
    total_count = 0

    for element in nested_list:
        if isinstance(element, list):
            inner_sum, inner_count = calculate_average(element)
            total_sum += inner_sum
            total_count += inner_count
        else:
            total_sum += element
            total_count += 1

    return total_sum, total_count

nested_list = [1, [2, [3, 4], 5], [[6, 7], 8], 9]
sum_elements, count_elements = calculate_average(nested_list)
average = sum_elements / count_elements if count_elements != 0 else 0
print("Average:", average)


Average: 5.0


# About a Numpy.

In [ ]:
import numpy as np
# initialize an all zero array with size 2 X 3:
zeros_arr = np.zeros((2,3))
print(" A zeros array is \n", zeros_arr, "with dimensions", zeros_arr.shape, "\n")

 A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]] with dimensions (2, 3) 



In [ ]:
import numpy as np
# initialize an all zero array with size 2 X 3:
zeros_arr = np.zeros((2,3))
print(" A zeros array is \n", zeros_arr, "with dimensions", zeros_arr.shape, "\n")

 A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]] with dimensions (2, 3) 

